steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'worker/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/chatgpt-security-scanner', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chatgpt-security-scanner']
  
  # Deploy the new image to all Cloud Run services without overriding console-managed settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','chatgpt-security-scanner','--image','gcr.io/$PROJECT_ID/chatgpt-security-scanner','--region','us-central1','--platform','managed','--quiet']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','chatgpt-security-scanner-1','--image','gcr.io/$PROJECT_ID/chatgpt-security-scanner','--region','us-central1','--platform','managed','--quiet']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','chatgpt-security-scanner-2','--image','gcr.io/$PROJECT_ID/chatgpt-security-scanner','--region','us-central1','--platform','managed','--quiet']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','chatgpt-security-scanner-3','--image','gcr.io/$PROJECT_ID/chatgpt-security-scanner','--region','us-central1','--platform','managed','--quiet']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','chatgpt-security-scanner-4','--image','gcr.io/$PROJECT_ID/chatgpt-security-scanner','--region','us-central1','--platform','managed','--quiet']

images:
  - 'gcr.io/$PROJECT_ID/chatgpt-security-scanner'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
