steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/enterprise-semgrep-scanner:$COMMIT_SHA', './worker']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/enterprise-semgrep-scanner:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'enterprise-semgrep-scanner'
      - '--image'
      - 'gcr.io/$PROJECT_ID/enterprise-semgrep-scanner:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '10'
      - '--max-instances'
      - '5'

# Store images in Google Cloud Storage
images:
  - 'gcr.io/$PROJECT_ID/enterprise-semgrep-scanner:$COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
