# Worker Configuration for Horizontal Scaling
worker_instances: 5
min_instances_per_worker: 4
max_instances_per_worker: 20

# Scaling Configuration
scaling_config:
  cpu: 2
  memory: "2Gi"
  timeout: 900
  concurrency: 1
  cpu_throttling: true
  cpu_boost: true

# API Key Distribution (4 keys per worker)
api_key_distribution:
  keys_per_worker: 4
  total_keys_needed: 20
  distribution:
    - worker: "chatgpt-security-scanner"
      keys: ["OPENAI_API_KEY", "OPENAI_API_KEY_1", "OPENAI_API_KEY_2", "OPENAI_API_KEY_3"]
    - worker: "chatgpt-security-scanner-1"
      keys: ["OPENAI_API_KEY", "OPENAI_API_KEY_1", "OPENAI_API_KEY_2", "OPENAI_API_KEY_3"]
    - worker: "chatgpt-security-scanner-2"
      keys: ["OPENAI_API_KEY", "OPENAI_API_KEY_1", "OPENAI_API_KEY_2", "OPENAI_API_KEY_3"]
    - worker: "chatgpt-security-scanner-3"
      keys: ["OPENAI_API_KEY", "OPENAI_API_KEY_1", "OPENAI_API_KEY_2", "OPENAI_API_KEY_3"]
    - worker: "chatgpt-security-scanner-4"
      keys: ["OPENAI_API_KEY", "OPENAI_API_KEY_1", "OPENAI_API_KEY_2", "OPENAI_API_KEY_3"]

# Sharding Configuration
sharding:
  enabled: true
  min_files_threshold: 300
  max_workers_per_scan: 2
  batch_size: 50
  peer_workers:
    - "chatgpt-security-scanner-1"
    - "chatgpt-security-scanner-2"
    - "chatgpt-security-scanner-3"
    - "chatgpt-security-scanner-4"

# Deployment
deployment:
  region: "us-central1"
  platform: "managed"
  allow_unauthenticated: true
  memory: "2Gi"
  cpu: 2
  timeout: 900
  min_instances: 4
  max_instances: 20
  concurrency: 1
  cpu_throttling: true
  cpu_boost: true

monitoring:
  health_check_interval: 30   # Health check every 30 seconds
  health_check_timeout: 10    # Health check timeout in seconds
  health_check_retries: 3     # Number of retries before marking unhealthy

# Load balancing strategy:
# - Round-robin distribution of new scans across workers
# - Each worker handles 1 scan at a time
# - Auto-scaling within each worker service based on demand
# - Fallback to other workers if one becomes unavailable
